### ISSUE TITLE
搜狗云工作不正常。

### ISSUE THREAD

**Issue by iesvme** [summershrimp/obs-auto-subtitle#31]
没有反应，多次点击“启用翻译”时，搜狗云会不显示下面的填写框。
![image](https://user-images.githubusercontent.com/16969250/143216045-4b9d9d4e-230d-4604-b266-24a751b44c74.png)
并且填写了搜狗的内容后，讯飞框就会重复出现搜狗的内容！

**Comment by summershrimp** [comment]
搜狗目前尚未支持，只是占位符
