### ISSUE TITLE
提示 websocket error

### ISSUE THREAD

**Issue by quick220** [summershrimp/obs-auto-subtitle#38]
其他设置正确，但是提示websocket error

**Comment by euukey** [comment]
怎么解决的，我开始几秒都可以，后面就显示这个了

**Comment by summershrimp** [comment]
> 怎么解决的，我开始几秒都可以，后面就显示这个了

请留下具体的错误信息，最好上传日志并。单从“websocket error ”两个单词 无法分析错误原因
