### ISSUE TITLE
How to use it？

### ISSUE THREAD

**Issue by d14ktb** [summershrimp/obs-auto-subtitle#54]
I am a novice. I saw this plug-in and felt very interesting.
I registered this page and want to ask how to use it.
·
我在找obs的弹幕姬（支持斗鱼），所以去看了obs官网的插件页面，然后看到了这个。
我已经安装完，也知道如何卸载，但我不知道怎么实现这个效果，我不懂代码，也不太懂obs。
如果用那些语音转文字的服务商，价钱会很贵吗？如果贵的话游戏和日常直播好像就负担不太起...

**Comment by d14ktb** [comment]
https://toscode.mulanos.cn/xm1994/obs-auto-subtitle
我去找教程了，刚找到教程回来看页面也发现了教程，也不知道是刚刚我眼瞎还是刚更新。
话说连教程都一模一样...

**Comment by summershrimp** [comment]
This is a plugin that generate subtitle by your voice, not a plugin shows damaku in your live room.
This plugin depends on cloud provider to provide real time speech-to-text service, and yes it's a little expensive.
Please ask beginners question on community QQ group or Discord, not on Issue.
