### ISSUE TITLE
除了语音识别希望能添加翻译功能

### ISSUE THREAD

**Issue by ilai11** [summershrimp/obs-auto-subtitle#56]
除了语音识别希望能添加翻译功能，谢谢

**Comment by summershrimp** [comment]
已有功能，请仔细阅读介绍

**Comment by ilai11** [comment]
> 已有功能，请阅读以下链接 https://www.bilibili.com/read/cv11354299

好的，谢谢。不过不知道有没有添加别的翻译引擎的计划呢，讯飞翻译用的就是小牛翻译的引擎，但是讯飞收费并且价格较高，而小牛本身是免费的，翻译质量一般。翻译质量相对较好的是deepl，其次是谷歌，国内的话可以百度，腾讯，小牛。
