### ISSUE TITLE
Mac m1 can not load plugin

### ISSUE THREAD

**Issue by yinzhidong** [summershrimp/obs-auto-subtitle#57]
1. log详情
09:49:52.907: os_dlopen(/Users/echo/Library/Application Support/obs-studio/plugins/obs-auto-subtitle.plugin/Contents/MacOS/obs-auto-subtitle->/Users/echo/Library/Application Support/obs-studio/plugins/obs-auto-subtitle.plugin/Contents/MacOS/obs-auto-subtitle): dlopen(/Users/echo/Library/Application Support/obs-studio/plugins/obs-auto-subtitle.plugin/Contents/MacOS/obs-auto-subtitle, 0x0101): Symbol not found: (__ZN9QtPrivate25QMetaTypeInterfaceWrapperI7QStringE8metaTypeE)
09:49:52.907:   Referenced from: '/Users/echo/Library/Application Support/obs-studio/plugins/obs-auto-subtitle.plugin/Contents/MacOS/obs-auto-subtitle'
09:49:52.907:   Expected in: '/Applications/OBS.app/Contents/Frameworks/QtCore.framework/Versions/A/QtCore'
09:49:52.907: 
09:49:52.907: Module '/Users/echo/Library/Application Support/obs-studio/plugins/obs-auto-subtitle.plugin/Contents/MacOS/obs-auto-subtitle' not loaded

2. OBS版本
28.0.1(64bit)

3. 操作系统
MacOS M1

貌似错误是：Symbol not found: (__ZN9QtPrivate25QMetaTypeInterfaceWrapperI7QStringE8metaTypeE)，不知道是不是QT的原因。

**Comment by summershrimp** [comment]
插件是什么版本？最新版插件仅支持obs 29以上


yinzhidong ***@***.***> 于 2023年4月4日周二 09:59写道：

**Comment by yinzhidong** [comment]
> 

感谢🙏，是我太大意了。
