### ISSUE TITLE
可否集成阿里离线识别模型

### ISSUE THREAD

**Issue by super-crayfish** [summershrimp/obs-auto-subtitle#64]
阿里离线识别模型参考链接
[modelscope](https://www.modelscope.cn/models/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/summary)
[github](https://github.com/alibaba-damo-academy/FunASR)

**Comment by summershrimp** [comment]
感谢提供信息！我会考虑的
