### ISSUE TITLE
滤镜里没有自动字幕

### ISSUE THREAD

**Issue by OaimIsGnay** [summershrimp/obs-auto-subtitle#65]
<img width="240" alt="image" src="https://github.com/summershrimp/obs-auto-subtitle/assets/58240619/a64410fe-d085-4cb7-8d1b-4dcbee3ed3e9">

**Comment by OaimIsGnay** [comment]
obs版本最新的 29.1.3  m1的macbok

**Comment by summershrimp** [comment]
Please read FAQ First
https://github.com/summershrimp/obs-auto-subtitle/wiki/FAQ
