### ISSUE TITLE
插件在obs V25.0.8 64位无法运行。

### ISSUE THREAD

**Issue by Danjuanlab** [summershrimp/obs-auto-subtitle#8]
目标文本源一直为none，测试只能识别已弃用的freetype 2的文本。猜测是在判断文本源的类型错了。(GDI+).另外好像搜狗AI也不行，一直在准备

**Comment by summershrimp** [comment]
处于跨平台考虑，目前仅支持了freetype2. 
搜狗AI由于不支持云端断句，因此还未支持。

**Comment by summershrimp** [comment]
目前在windows上仅支持讯飞的API

**Comment by Argeslim** [comment]
我安装好了没有之后该怎么做？

**Comment by summershrimp** [comment]
> 我安装好了，之后该怎么做？

说明已更新：
https://github.com/summershrimp/obs-auto-subtitle/blob/master/README-zh.md

**Comment by whity233** [comment]
讯飞在win10不起作用 文本一直是Preparing

**Comment by summershrimp** [comment]
> 讯飞在win10不起作用 文本一直是Preparing

请确保讯飞账户已经通过个人/企业认证，并已购买对应套餐。下一个版本会将api返回的错误信息显示在字幕中。

**Comment by summershrimp** [comment]
0.2.1版已更新

**Comment by charlesXu86** [comment]
我安装好了，但是在添加阿里云的appkey和token的时候，程序就莫名退出了，请问这个是由于obs的版本问题导致的吗？

**Comment by summershrimp** [comment]
> 我安装好了，但是在添加阿里云的appkey和token的时候，程序就莫名退出了，请问这个是由于obs的版本问题导致的吗？

请添加QQ群并且上传崩溃日志
